management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    httptrace:
      enabled: true
    metrics:
      enabled: true
    threaddump:
      enabled: true
    health:
      show-details: always

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  rabbitmq:
    addresses: 172.16.1.175:5672
    username: cloud
    password: cloud
    virtual-host: cloud

  zipkin:
    #使用http方式发送链路追踪数据
    #base-url: http://localhost:9411
    #使用rabbitmq方式发送链路追踪数据
    sender:
      type: rabbit
    #此设置不支持动态刷新
    rabbitmq:
      queue: cloudzipkin

  sleuth:
    sampler:
      probability: 1.0

server:
  port: 9000

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  ignoredServices: "*"
  prefix: /api
  routes:
    user-client: /user/**
